<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Phm Vn Mnh_dropdownMenu1</name>
   <tag></tag>
   <elementGuidId>eeff63bc-802b-4b19-8bbd-1e6af4687705</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dropdownMenu1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropdownMenu1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d0c8ff9e-1374-40f6-b904-c16646a2a139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-shadow btn-auth dropdown-toggle</value>
      <webElementGuid>cd6b3747-eb05-4ed9-9f2f-005accec7f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c2a231d9-2245-4456-ae96-0b01e8e0363e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdownMenu1</value>
      <webElementGuid>2b3742c0-90f6-4ab2-b320-83d928e2805e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>f785dc37-088a-44c5-ab72-1ace6ff76b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>58613abc-dfd3-4d96-8926-a37eb36bebf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dc0145d7-fff6-4918-ae17-8866093665a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Phạm Văn Mạnh
                        
                    </value>
      <webElementGuid>fd2cb892-bba9-46f7-8c3f-f052b4637b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdownMenu1&quot;)</value>
      <webElementGuid>bafd4dd5-a72f-4c0f-90c4-871b1f40d798</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dropdownMenu1']</value>
      <webElementGuid>22dda6e8-904c-4ad6-86f7-0c4eb9365fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headwrap']/div[3]/div/button</value>
      <webElementGuid>4c1b65bd-929e-4aa0-be3b-4e86216c299c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tài khoản'])[1]/preceding::button[1]</value>
      <webElementGuid>60eba20b-263c-4877-a46f-c947e7a7434a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>f662e693-baf4-48ac-a09f-8721fbd81e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'dropdownMenu1' and (text() = '
                        Phạm Văn Mạnh
                        
                    ' or . = '
                        Phạm Văn Mạnh
                        
                    ')]</value>
      <webElementGuid>25c11b78-30d4-4991-a5f5-2fb03a7fbe55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
