<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>email_datontai</name>
   <tag></tag>
   <elementGuidId>6b63de1d-407b-4c52-96b4-9ee12eb0a938</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#error-register</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='error-register']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f1a710f4-d0e1-4014-85cc-4e068f44bd22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-group alert alert-danger</value>
      <webElementGuid>4674c2d3-4b19-422a-8214-1f695ca81ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>error-register</value>
      <webElementGuid>a8d9ff01-ea9a-4f81-b882-efeb5b789aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email đã tồn tại</value>
      <webElementGuid>d544d868-1259-4100-b46d-6f97c496f360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;error-register&quot;)</value>
      <webElementGuid>742792b0-5efd-44cc-8112-b04f6efd8cfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='error-register']</value>
      <webElementGuid>cf7d6c48-2e3e-44f6-b432-f84ac3f61f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-register']/div[2]/div/div</value>
      <webElementGuid>451a2656-7064-472d-84e2-62ef85d14a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[3]/following::div[6]</value>
      <webElementGuid>f9750d9d-e2ab-4752-bd12-a2f87218693c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đóng'])[1]/following::div[6]</value>
      <webElementGuid>9008e468-3698-4dd7-a15f-aaa4fd7d5557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tên:'])[1]/preceding::div[1]</value>
      <webElementGuid>34687305-a72e-42c7-a8f9-88c20f5c1a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email:'])[2]/preceding::div[2]</value>
      <webElementGuid>5a86bb90-8675-4298-9955-572deb847a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email đã tồn tại']/parent::*</value>
      <webElementGuid>3b0ddf32-3f24-4fff-a443-2592e54103e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/form/div[2]/div/div</value>
      <webElementGuid>58693587-4af3-4dce-983a-41c2f21333ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'error-register' and (text() = 'Email đã tồn tại' or . = 'Email đã tồn tại')]</value>
      <webElementGuid>40bbcd14-f8dc-4db6-be44-6c0df6eebd60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
